version: "3.7"
networks:
  autovmaf-internal:
    driver: bridge

services:
  autovmaf-api:
    depends_on:
      - redis
    build:
      context: .
    image: autovmaf-worker
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - autovmaf-internal
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - autovmaf-internal
