version: "3.7"
networks:
  autoabr-internal:
    driver: bridge

services:
  autoabr-api:
    build:
      context: .
    image: autoabr-worker
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LAMBDA=true
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - autoabr-internal
